name: 'PROD Docker Image'

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: ".*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smartenergyplatform/moses:prod
            ghcr.io/senergy-platform/moses:prod
            smartenergyplatform/moses:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/senergy-platform/moses:${{ steps.tag_version.outputs.new_tag }}
            smartenergyplatform/moses:latest
            ghcr.io/senergy-platform/moses:latest
